In [15]:
# 지도 그래프
import folium
import pandas as pd

In [16]:
# 서울 지도 만들기
seoul_map2 = folium.Map(location=[37.55,126.98], tiles='Stamen Terrain', 
                        zoom_start=12)
seoul_map3 = folium.Map(location=[37.55,126.98], tiles='Stamen Toner', 
                        zoom_start=15)

# 지도를 HTML 파일로 저장하기
seoul_map2.save('./dataset/seoul2.html')
seoul_map3.save('./dataset/seoul3.html')

In [39]:
# 마커 추가
df = pd.read_excel("./dataset/data/서울지역 대학교 위치.xlsx")

seoul_map = folium.Map(location=[37.55,126.98], tiles= 'Stamen Terrain',
                      zoom_start= 12)

df.rename(columns={'Unnamed: 0': 'name'},inplace=True)
df.set_index('name', inplace=True)


for name, lat, lng in zip(df.index, df.위도, df.경도):
    folium.Marker([lat, lng], popup=name).add_to(seoul_map)
    
seoul_map.save('./dataset/seoul.html')

                       위도          경도
name
KAIST 서울캠퍼스     37.592573  127.046737
KC대학교           37.548345  126.854797
가톨릭대학교(성신교정)    37.585922  127.004328
가톨릭대학교(성의교정)    37.499623  127.006065
감리교신학대학교        37.567645  126.961610
건국대학교           37.540762  127.079343
경기대학교 서울캠퍼스     37.300485  127.035833
경희대학교 서울캠퍼스     37.596195  127.052544
고려대학교           33.847782 -117.977748
광운대학교           37.619496  127.059696
국민대학교           37.609641  126.997697
덕성여자대학교         37.651199  127.016160
동국대학교           37.557477  127.002052
동덕여자대학교         37.606320  127.041808
명지대학교 서울캠퍼스     37.580205  126.923445
삼육대학교           37.642952  127.105476
상명대학교 서울캠퍼스     37.602638  126.955252
서강대학교           37.550944  126.941002
서경대학교           37.615095  127.013111
서울과학기술대학교       37.631668  127.077481
서울교육대학교         37.489961  127.016412
서울기독대학교         37.600923  126.912382
서울대학교           37.459882  126.951905
서울시립대학교         37.583866  127.058777
서울여자대학교         37.628113  127.090457
서울한영대학교         37.496541  126.851262
성공회대학교          37.487232  126.825320
성균관대학교 서울캠퍼스    37.588227  126.993606
성신여자대학교         37.591310  127.022131
세종대학교           37.550260  127.073139
숙명여자대학교         37.546364  126.964831
숭실대학교           37.496311  126.957460
연세대학교           37.565784  126.938572
육군사관학교          37.623819  127.098878
이화여자대학교         37.564308  126.950179
장로회신학대학교        37.550511  127.103458
중앙대학교 서울캠퍼스     37.505088  126.957101
총신대학교           37.488623  126.966817
추계예술대학교         37.562452  126.953417
한국방송통신대학교       37.578613  127.003291
한국성서대학교         37.648749  127.064320
한국예술종합학교        37.604997  127.056740
한국외국어대학교        37.597319  127.057843
한국체육대학교         37.519627  127.130984
한성대학교           37.581785  127.010369
한양대학교           37.557232  127.045322
홍익대학교           37.551464  126.925011

In [43]:
# 써클 마커 추가
df = pd.read_excel("./dataset/data/서울지역 대학교 위치.xlsx")
seoul_map = folium.Map(location=[37.55,126.98], tiles= 'Stamen Terrain',
                      zoom_start= 12)

df.rename(columns={'Unnamed: 0': 'name'},inplace=True)
df.set_index('name', inplace=True)


for name, lat, lng in zip(df.index, df.위도, df.경도):
    folium.CircleMarker([lat, lng],
                    radius=10,         # 원의 반지름
                    color='brown',     # 원의 둘레 색상
                    fill=True,
                    fill_color='coral', # 원을 채우는 색
                    fill_opacity=0.7, # 투명도
                    popup=name).add_to(seoul_map)
    
seoul_map.save('./dataset/seoul.html')